/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;

/**
 *
 * @author ulacit
 */
public class matrix extends javax.swing.JPanel {

    static void setPanel(PanelBarcos panelBarcos2) {
        matrix.panel = panelBarcos2;
    }
   public JButton[][] MatrizUsuario;
   public boolean ColocandoBarcos = true;
   public boolean TurnoJugador = false;
   private static PanelBarcos panel;
   // private Casilla CasillaUsuario;
   public void restartMatrix(){
       for (int i=0;i<10;i++)
           for (int b=0;b<10;b++)
                this.MatrizUsuario[i][b].setBackground(Color.DARK_GRAY);
   }
   // private Casilla[][] MatrizCasillasUsuario;
    /**
     * Creates new form matrix
     */
    public matrix() {
        initComponents();
        CreaMatrizUsuario();
    }
    private void CreaMatrizUsuario() {
        this.MatrizUsuario = new JButton[10][10];
       // this.MatrizCasillasUsuario = new Casilla[15][15];
        for (int fila = 0; fila < 10; fila++) {
            for (int columna = 0; columna < 10; columna++) {
         //       this.MatrizCasillasUsuario[fils][colums] = this.CasillaUsuario;
                Casilla boton = new Casilla(fila,columna);
                this.add(boton);
                boton.setBounds(20 + (fila * 30), 30 + (columna * 30), 30, 30);
                boton.setBackground(Color.DARK_GRAY);
                this.MatrizUsuario[fila][columna] = boton;
                MatrizUsuario[fila][columna].setActionCommand(fila + "," + columna);
                MatrizUsuario[fila][columna].addMouseListener(new MouseAdapter() {//aclickSobreTablero(evt);ñade el listener al boton

                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        if (boton.getBackground()==Color.DARK_GRAY){
                            if(ColocandoBarcos){
                                System.out.println(matrix.panel.getAlineacion());
                                System.out.println(matrix.panel.getShipSize());
                                boton.setBackground(Color.red);
                                System.out.println("Fila: "+boton.getFila());
                                System.out.println("Columna: "+boton.getColumna());
                            }
                            if(TurnoJugador){
                                boton.setBackground(Color.blue);
                                System.out.println("Fila: "+boton.getFila());
                                System.out.println("Columna: "+boton.getColumna());                            
                            }
                      
                        }
                    }
                    
                });
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
